id: P9430E2CF
initial_creation_type: input
source_metadata:
  title: Sādhanas Series
  language: bo
  description: 'Lotsawa House presents the following sādhanas (sgrub thabs). (Please
    note that you may need to receive empowerment, transmission and instructions from
    a qualified lineage-holder before putting these sādhanas into practice):'
  volume:
    cb6649f5d3304cde9e5e7ab2851080c7:
      title: Acala Sādhana
      parent: Acala
    3942cf7429fc4b34b055470617280513:
      title: A Daily Practice of Buddha Akṣobhya
      parent: Akṣobhya
    97a4df68aa5f41beb5c526d9b40c541c:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Amitāyus
    c11bb12aeb164ffb9308963c96ac8443:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Amitāyus
    817917e3c43a4220aa2caab9b1364c26:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Amitāyus
    3880aa9ef98b42e0a35717ba760546d0:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Avalokiteśvara
    c1b3e23b80bc46c2bb9939ee4ef1b945:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Avalokiteśvara
    7d42e6dd68f348a8bf626b0fdbd38d72:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Avalokiteśvara
    1443c2ab883d4ad08ec2ccac708f1c22:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Avalokiteśvara
    e45783520f284b14a327c9ae6d8f5867:
      title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in
        the Union of Generation and Completion'
      parent: Avalokiteśvara
    635c00fc4b1d47e791c8ea6892cd0ddf:
      title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization
        and Mantra Recitation of the Great Compassionate One'
      parent: Avalokiteśvara
    8e9cfc85a9774823a7f59468be85b804:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Buddha Śākyamuni
    f5fc98fe32eb45baa30b376be3646c1f:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Buddha Śākyamuni
    7efa2e69a4de4f32846dd5ff3abe3472:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Buddha Śākyamuni
    8d39ddf7ad954676b51ce8f6fd88f2b4:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Buddha Śākyamuni
    e99833c78d6b4942a4beddc47872b8ec:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Dorje Drolö
    1bb4ba06e2e34cfeb4cdde536c1f16b7:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Dorje Drolö
    97e0e44c9c6f4ecb9af787598afb7add:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Dükyi Shechen
    660a2e5428ce4fd290823835fd0ab9ac:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Guru Dewa Chenpo
    37949cb20cae4218b6e1e8a87a8e8cab:
      title: Daily Practice of Guru Drakpo
      parent: Guru Drakpo
    bd0da97d875c4623961b4c2334fde868:
      title: Increasing Intelligence – Sealed with Profundity
      parent: Guru Loden Chokse
    6a8a2178020344e09abbcba332376375:
      title: Daily Practice of Hayagrīva
      parent: Hayagrīva
    21864a49f2c64da5bf37c808947a4af6:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Hayagrīva
    bad58ec3f5264a298217303dcc6f2e8c:
      title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth
        Deity White Jambhala'
      parent: Jambhala
    389ecab1b62b46328425071416222b4c:
      title: A Sādhana of Jambhala
      parent: Jambhala
    796e640349aa44a88e4cd7173962f314:
      title: Daily Practice of Kagyé
      parent: Kagyé
    966ef59c31ca4442bfb660d0d9aea42c:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Kurukullā
    9cd3b52ac6004299964bde4cb9bdebbe:
      title: A Sādhana of Kurukullā
      parent: Kurukullā
    fd57ef736b73429a85ca379c617599f1:
      title: A Daily Practice of Lama Sangdü
      parent: Lama Sangdü
    6852ce8641024c4cab5e8ab769888f25:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Lama Sangdü
    5bf0821f8769418fa84b4f5de7ccf30e:
      title: Light from the Wisdom Sun
      parent: Mañjuśrī
    443f47bf05034521a7f753784f7d110b:
      title: A Sādhana of Golden Mañjughoṣa
      parent: Mañjuśrī
    ed0b45b1112842d292535be7ae739e60:
      title: 'Swift Bestowal of Blessings: A Peaceful Sādhana of Mañjuśrī'
      parent: Mañjuśrī
    4da5fd0648214a9a9bfe285e604ecdb8:
      title: A Brief Mañjuśrī Sādhana
      parent: Mañjuśrī
    4c8c89607f5945baafb22bde976addfa:
      title: Sādhana of Mañjughoṣa
      parent: Mañjuśrī
    fbabea7616764128b98b5cef021e50dc:
      title: A Sādhana of Mārīcī
      parent: Mārīcī
    5190adee3fc049d29a95d5d98076b0d8:
      title: Sādhana of Mārīcī
      parent: Mārīcī
    08b84ff588e5425fb419c729ace9f96b:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Medicine Buddha
    6a1b2fd926e04eec8acbccffb47fea01:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Medicine Buddha
    d7f0ed96cfa74c43ac609fcf129684bb:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Medicine Buddha
    6893c3f2b86a4ae89bf6b434b89ff30e:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Peaceful & Wrathful Deities
    a5c83746f5214018b59f500cd6662f9f:
      title: A Brief Visualization and Recitation of the Great Mother Prajñāpāramitā
      parent: Prajñāpāramitā
    bf1a7a59214242dc9b28742640aa9b24:
      title: A Sādhana of Tārā Sarasvatī
      parent: Sarasvatī
    3e30b647ffbf4569830d37b3c6e883c4:
      title: A Sādhana of White Sarasvatī
      parent: Sarasvatī
    5fa0cae51ee8465eb30e41a7e2df8321:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sarasvatī
    73b4ec7e73bd49d3b14413381b9bd167:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    f0f9610657f94d2eb178153ef9b3b52b:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sitātapatrā
    5a27f4253207414d923b4ae7067c3359:
      title: 'The Swift Steed of Garuḍa, King of Birds: An Instruction for Travelling
        to Sukhāvatī: A Visualization and Recitation of Uṣnīṣa-Sitātapatrā'
      parent: Sitātapatrā
    c6e128fdf61148d4b00dab3ca56219df:
      title: A Sādhana of Sitātapatrā
      parent: Sitātapatrā
    e30fc3700f6945fa809bb2fe9d6f55e8:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Takhyung Barwa
    f1301645e11840bb8d9b95ee97297b2f:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Tārā
    387cf5c114b443a2b3e4438b5b41de1f:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Tārā
    04343b922225449dad767f4fce619947:
      title: Concise White Tārā Sādhana
      parent: Tārā
    f4e5f8a5a2f441eda20a4956ea642f02:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Tārā
    a7e9e51039b848a98aa40de9e8b68c04:
      title: 'A Shower of Blessings: A Sādhana of Blue-Green Tārā'
      parent: Tārā
    8832b9fadc564609aa6dce74ab1f62d5:
      title: A Daily Practice of Ucchuṣma
      parent: Ucchuṣma
    fa6f7a3c61ee4ac8be45d6b9f879114e:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Ucchuṣma
    a15d8b2439e14358a179593b8c3229ac:
      title: Daily Practice of Vajrakīla
      parent: Vajrakīla
    89eb4ca05b5c42feb61abdb06e0aad57:
      title: The Essential Daily Practice of Vajrakīla
      parent: Vajrakīla
    8700355e64024f0098c4ff9caac143ba:
      title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual
        for The Vajrakīla Root Tantra Section'
      parent: Vajrakīla
    a841c7ba7bc440189667f08857e85300:
      title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle'
      parent: Vajrakīla
    9ba33d808e9948fc80a7bfeb2e5c02eb:
      title: The Single Mind Kīla Practice, Part of the 'Neck-Pouch Dagger’ (Purba
        Gulkhukma) Cycle
      parent: Vajrakīla
    2be75be86cdf4331890ca24eb410d308:
      title: The Wisdom Mind Practice of One Kīla
      parent: Vajrakīla
    93739ad4f413417dbebf2b2d4e20b561:
      title: Concise Daily Practice of Vajrasattva
      parent: Vajrasattva
    6bf46ac1e0e14c36b6c837a43d7cffae:
      title: Brief Vajrasattva Visualisation and Mantra Recitation
      parent: Vajrasattva
    b0d34cf33d2043f7916a05287ca26b21:
      title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the
        Glorious Vajrasattva, a Method of Purification and Accomplishment for Both
        Self and Others'
      parent: Vajrasattva
    9f75564aaed841ca850d3c22f8fb7c90:
      title: Daily Practice of Mañjuśrī Yamāntaka
      parent: Yamāntaka
    3118d43d693e4dc694f56c2d19ce170d:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Yeshe Tsogyal
    57856bd564154085af1f812f2f6d4e0d:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Yumka Dechen Gyalmo
    09d91f3cf6a5421bb3edb48cb51e817b:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    6dc91310d73541a3ad15d66c7d99d410:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-03-01T05:36:59.663268'
last_modified_at: '2022-03-01T05:36:59.663271'
statistics:
  total_words: 49821
  total_non_words: 6439
quality:
  non_words_ratio: 0.13
